spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: mongodb+srv://vvrurlshrinker:vvrurlshrinker@vvr-url-shrinker-lukds.mongodb.net/vvrurlshrinker?retryWrites=true&w=majority
      database: vvrurlshrinker

server:
  port: 8888